name: Tests

on:
  push:
  pull_request:

env:
  API_BASE_URL: https://practice.expandtesting.com/notes/api
  BASE_URL: https://practice.expandtesting.com/notes/app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Run API tests
        run: |
          pytest tests/api \
            --html=api-report.html \
            --junitxml=api-results.xml

      - name: Run Integration tests
        env:
          HEADLESS: true
        run: |
          pytest tests/integration \
            --html=integration-report.html \
            --junitxml=integration-results.xml

      - name: Upload API reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-reports
          path: |
            api-report.html
            api-results.xml

      - name: Upload Integration reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-reports
          path: |
            integration-report.html
            integration-results.xml