name: Tests

on:
  push:
  pull_request:

env:
  API_BASE_URL: https://practice.expandtesting.com/notes/api
  BASE_URL: https://practice.expandtesting.com/notes/app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install chromium

      - name: Run API tests
        run: pytest tests/api

      - name: Run tests
        env:
          HEADLESS: true
        run: pytest tests/integration